export const WORDS = [
  "i", "you", "to", "the", "a", "and", "is", "it", "my", "me", "please", "yes", "no",
  "am", "need", "want", "feel", "have", "can", "could", "would", "will", "do", "don't",
  "can't", "not", "now", "help", "thank", "thanks", "okay", "good", "sorry", "love",
  "in", "on", "of", "for", "with", "but", "so", "too", "very", "just", "more", "some",
  "water", "food", "drink", "medicine", "medication", "pain", "hurts", "hurting",
  "tired", "hungry", "thirsty", "cold", "hot", "warm", "sick", "dizzy", "scared",
  "uncomfortable", "comfortable", "itchy", "breathe", "breathing", "rest", "sleep",
  "nurse", "doctor", "family", "mother", "mom", "father", "dad", "wife", "husband",
  "son", "daughter", "friend", "phone", "bathroom", "toilet", "bed", "pillow", "blanket",
  "light", "lights", "window", "door", "tv", "music", "room", "chair", "head", "back",
  "leg", "legs", "arm", "arms", "hand", "hands", "feet", "mouth", "eyes", "chest", "stomach",
  "here", "there", "come", "go", "stay", "stop", "wait", "move", "turn", "open", "close",
  "bring", "call", "tell", "ask", "give", "take", "make", "let", "show", "look", "see",
  "hear", "talk", "speak", "say", "know", "think", "feeling", "better", "worse", "fine",
  "morning", "night", "today", "tomorrow", "soon", "later", "again", "still", "almost",
  "this", "that", "what", "when", "where", "who", "why", "how", "yourself", "myself",
  "we", "they", "he", "she", "him", "her", "us", "them", "your", "our", "their", "his",
  "are", "was", "were", "be", "been", "being", "if", "or", "because", "about", "up", "down",
  "off", "out", "right", "left", "thank you", "everything", "something", "anything",
  "nothing", "everyone", "someone", "people", "thing", "time", "day", "little", "much",
];

export const SYNONYMS = {
  medicine: "medicine", medication: "medicine",
  mother: "parent-mom", mom: "parent-mom",
  father: "parent-dad", dad: "parent-dad",
  thank: "thanks", thanks: "thanks",
  feel: "feel", feeling: "feel",
  breathe: "breathe", breathing: "breathe",
  hurts: "hurt", hurting: "hurt",
  leg: "leg", legs: "leg",
  arm: "arm", arms: "arm",
  hand: "hand", hands: "hand",
  eye: "eye", eyes: "eye",
  light: "light", lights: "light",
};

export const BIGRAMS = {
  i: ["am", "need", "want", "feel", "can't", "would", "don't", "love", "have", "will", "think"],
  "i'm": ["in", "too", "not", "feeling", "okay", "scared", "fine", "hungry", "thirsty", "cold", "hot", "tired"],
  am: ["in", "feeling", "not", "okay", "scared", "hungry", "thirsty", "cold", "hot", "tired"],
  need: ["some", "to", "my", "help", "water", "the", "a", "more", "you"],
  want: ["to", "some", "my", "a", "you", "water", "more"],
  feel: ["sick", "cold", "hot", "tired", "scared", "better", "fine", "dizzy", "uncomfortable"],
  feeling: ["sick", "cold", "hot", "tired", "scared", "better", "dizzy", "uncomfortable"],
  "can't": ["breathe", "sleep", "move", "see", "hear", "feel"],
  please: ["help", "call", "come", "stop", "wait", "bring", "stay"],
  could: ["you", "i", "we"],
  you: ["please", "help", "come", "bring", "call", "turn", "stay"],
  thank: ["you"],
  turn: ["on", "off", "me"],
  call: ["my", "the", "a", "for"],
  the: ["bathroom", "nurse", "doctor", "light", "tv", "window", "pain", "room", "phone", "door"],
  my: ["family", "medicine", "head", "back", "leg", "arm", "phone", "wife", "husband", "mouth", "chest", "pillow"],
  to: ["the", "rest", "sleep", "go", "move", "eat", "drink", "talk"],
  some: ["water", "food", "rest", "help", "medicine"],
  bring: ["me", "my", "the"],
  come: ["here", "closer", "back"],
  in: ["pain", "the", "bed", "my"],
  too: ["hot", "cold", "tired", "much", "bright", "loud"],
  it: ["hurts", "is", "again"],
};

export const PHRASES = [
  "I'm in pain.", "I can't breathe.", "I need help.", "I need help now.",
  "I need some water.", "I need to use the bathroom.", "I need my medicine.",
  "I'm too hot.", "I'm too cold.", "I feel sick.", "I'm tired.", "I'd like to rest.",
  "I'm scared.", "Please stay with me.", "Please come closer.", "Please call my family.",
  "Please call the nurse.", "Please call the doctor.", "Could you turn on the light?",
  "Could you help me move?", "Could you bring me my phone?", "I love you.",
  "Thank you.", "Yes, please.", "No, thank you.", "I'm okay.", "I'm not okay.",
  "I don't know.", "Please wait a moment.", "Please stop.", "I'd like to sleep now.",
  "Good morning.", "Goodnight.", "How are you?", "I'm hungry.", "I'm thirsty.",
];

export const STARTERS = [
  "I need help.", "I'm in pain.", "Yes", "No", "Please", "I need", "I feel", "Could you",
];
